export { default as Root } from './Dialog.vue'
export { default as Close } from './DialogClose.vue'
export { default as Trigger } from './DialogTrigger.vue'
export { default as Header } from './DialogHeader.vue'
export { default as Title } from './DialogTitle.vue'
export { default as Description } from './DialogDescription.vue'
export { default as Content } from './DialogContent.vue'
export { default as Footer } from './DialogFooter.vue'
